name: ci
on:
  push:
    branches:
      - master
      - tags
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: make test

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Image
        run: make push
